export enum SchoolSubject {
  Mathematics = 'Matemática',
  History = 'História',
  Chemistry = 'Química',
  Physics = 'Física',
  English = 'Inglês',
  Geography = 'Geografia',
  Biology = 'Biologia',
  Portuguese = 'Português',
  Literature = 'Literatura',
  Philosophy = 'Filosofia',
  Sociology = 'Sociologia',
  PhysicalEducation = 'Educação Física',
  Arts = 'Artes',
  Spanish = 'Espanhol',
  ComputerScience = 'Informática',
  Technology = 'Tecnologia',
  Music = 'Música',
  Theater = 'Teatro',
}
